### ISSUE TITLE
Build Warnings

### ISSUE THREAD

**Issue by edent** [w3c/html#1215]
Probably worth fixing some of these - https://travis-ci.org/w3c/html/builds/342516738?utm_source=github_status&utm_medium=notification

WARNING: The following `<var>`s were only used once in the document. If these are not typos, please add an ignore='' attribute to the `<var>`.
 - [x] `  'scope'`
 - [x] `  'parser state'`
 - [x] `  'attr'`
 - [x] `  'classic script CORS setting'`
 - [x] `  'script settings object'`
 - [x] `  'parser metadata'`
 - [x] `  'top-level module fetch'`
 - [x] `  'text/'`
 - [x] WARNING: Multiple elements have the same ID 'determinate-progress-bar'. Deduping, but this ID may not be stable across revisions.
 - [x] WARNING: Multiple elements have the same ID 'indeterminate-progress-bar'. Deduping, but this ID may not be stable across revisions.
 - [x] LINK ERROR: No 'dfn' refs found for 'valid mime type with no parameters'. `<a data-link-type="dfn" data-lt="valid MIME type with no parameters">valid MIME type with no parameters</a>`
 - [ ] LINK ERROR: Ambiguous for-less link for 'referrer policy', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
   Local references:
     - `spec:html-5.3; type:dfn; for:/; text:referrer policy`
     - `spec:html-5.3; type:dfn; for:script; text:referrer policy`
  for-less references:
    - `spec:fetch; type:dfn; for:/; text:referrer policy `<a data-link-type="dfn" data-lt="referrer policy">referrer policy</a>`
 - [x] LINK ERROR: No 'idl' refs found for 'WebGL2RenderingContext'. `<a data-link-type="idl" data-lt="WebGL2RenderingContext">WebGL2RenderingContext</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'nonce'. `<a data-link-type="dfn" data-lt="nonce">nonce</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'becomes browsing-context connected'. `<a data-link-type="dfn" data-lt="becomes browsing-context connected">becomes browsing-context connected</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'document initialization'. `<a data-link-type="dfn" data-lt="Document initialization">Document initialization</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'has been shipped' that are marked for export. `<a data-link-type="dfn" data-lt="has been shipped">has been shipped</a>`
 - [ ] LINK ERROR: Ambiguous for-less link for 'csp list', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
   Local references:
   - `spec:html-5.3; type:dfn; for:document; text:csp list`
  for-less references:
   -  `spec:csp; type:dfn; for:/; text:csp list `<a data-link-type="dfn" data-lt="CSP list">CSP list</a>`
 - [ ] LINK ERROR: Ambiguous for-less link for 'referrer policy', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
  Local references:
  - `spec:html-5.3; type:dfn; for:/; text:referrer policy`
  - `spec:html-5.3; type:dfn; for:script; text:referrer policy`
  for-less references:
  - `spec:fetch; type:dfn; for:/; text:referrer policy <a data-link-type="dfn" data-lt="Referrer policy">Referrer policy</a>`
 - [ ] LINK ERROR: No 'dfn' refs found for 'rendering'. `<a data-link-type="dfn" data-lt="rendering">rendering</a>`
 - [x] LINK ERROR: No 'attr-value' refs found for 'menu'. `<a data-link-type="attr-value" data-link-for="aria/role" data-lt="menu"><code>menu</code></a>`
 - [x] LINK ERROR: No 'attr-value' refs found for 'menuitem'. `<a data-link-type="attr-value" data-link-for="aria/role" data-lt="menuitem"><code>menuitem</code></a>`
 - [x] LINK ERROR: No 'attr-value' refs found for 'menuitemcheckbox'. `<a data-link-type="attr-value" data-link-for="aria/role" data-lt="menuitemcheckbox"><code>menuitemcheckbox</code></a>`
 - [x] LINK ERROR: No 'attr-value' refs found for 'menuitemradio'. `<a data-link-type="attr-value" data-link-for="aria/role" data-lt="menuitemradio"><code>menuitemradio</code></a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'accessible name' that are marked for export. `<a data-link-type="dfn" data-lt="accessible name">accessible name</a>`
 - [x] LINK ERROR: No 'attr-value' refs found for 'menucheckbox'. `<a data-link-type="attr-value" data-link-for="aria/role" data-lt="menucheckbox"><code>menucheckbox</code></a>`
 - [x] LINK ERROR: No 'attr-value' refs found for 'menuradio'. `<a data-link-type="attr-value" data-link-for="aria/role" data-lt="menuradio"><code>menuradio</code></a>`
 - [x] LINK ERROR: No 'idl-name' refs found for 'RemotePlayback'. `<a data-link-type="idl-name" class="n" data-lt="RemotePlayback">RemotePlayback</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'absolute-anchored'. `<a data-link-type="dfn" data-lt="absolute-anchored">absolute-anchored</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'stripping leading and trailing whitespace'. `<a data-link-type="dfn" data-lt="stripping leading and trailing whitespace">stripping leading and trailing whitespace</a>`
 - [x] LINK ERROR: No 'idl-name' refs found for 'WebGL2RenderingContext'. `<a data-link-type="idl-name" class="n" data-lt="WebGL2RenderingContext">WebGL2RenderingContext</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'concept-host'. `<a data-lt="concept-host" data-link-type="dfn">host</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'concept-domain'. `<a data-lt="concept-domain" data-link-type="dfn">domain</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'concept-host'. `<a data-lt="concept-host" data-link-type="dfn">hosts</a>`
 - [ ] LINK ERROR: Ambiguous for-less link for 'origin', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
  Local references:
  - `spec:html-5.3; type:dfn; for:concept; text:origin`
  - `spec:html-5.3; type:dfn; for:security; text:origin`
  for-less references:
  - `spec:css-cascade-4; type:dfn; for:/; text:origin `<a data-link-type="dfn" data-lt="origin">origin</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'concept-origin-effective-domain'. `<a data-lt="concept-origin-effective-domain" data-link-type="dfn">effective domain.</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'concept-origin-effective-domain'. `<a data-lt="concept-origin-effective-domain" data-link-type="dfn"></a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'concept-origin-effective-domain'. `<a data-lt="concept-origin-effective-domain" data-link-type="dfn">If <var>effectiveDomain</var> is null, then throw a "<code class="idl" nohighlight=""><a data-link-type="idl" data-lt="SecurityError">SecurityError</a></code>" <code class="idl" nohighlight=""><a data-link-type="idl" data-lt="DOMException">DOMException</a></code>.</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'concept-origin-effective-domain'. `<a data-lt="concept-origin-effective-domain" data-link-type="dfn">If the given value <span data-x="is a registrable domain suffix of or is equal to">is not a registrable domain suffix of and is not equal to</span> <var>effectiveDomain</var> throw a "<code class="idl" nohighlight=""><a data-link-type="idl" data-lt="SecurityError">SecurityError</a></code>" <code class="idl" nohighlight=""><a data-link-type="idl" data-lt="DOMException">DOMException</a></code>.</a>`
 LINK ERROR: No 'dfn' refs found for 'concept-origin-effective-domain'. `<a data-lt="concept-origin-effective-domain" data-link-type="dfn">Set <var>origin</var>&#8217;s </a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'script record' that are marked for export. `<a data-link-type="dfn" data-lt="Script Record">Script Record</a>`
 - [ ] LINK ERROR: Multiple possible 'items' dfn refs. `Arbitrarily chose https://infra.spec.whatwg.org/#list-item`
  To auto-select one of the following refs, insert one of these lines into a `<pre class=link-defaults> block:
  - `spec:infra; type:dfn; for:tuple; text:item`
  - `spec:infra; type:dfn; for:stack; text:item`
  - `spec:infra; type:dfn; for:queue; text:item`
  - `spec:infra; type:dfn; for:list; text:item`
  - `spec:infra; type:dfn; for:pair; text:item`
  - `spec:infra; type:dfn; for:set; text:item`
  - `spec:infra; type:dfn; for:struct; text:item`
   `<a data-link-type="dfn" data-lt="items">items</a>`
 
 - [ ] LINK ERROR: Ambiguous for-less link for 'url', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
 Local references:
  - `spec:html-5.3; type:dfn; for:Location; text:url`
 for-less references:
  - `spec:url; type:dfn; for:/; text:url`
  - `<a data-link-type="dfn" data-lt="URL">URL</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'parser metadata is "not-parser-inserted", '. `<a data-link-type="dfn" data-lt='parser metadata is "not-parser-inserted", '>parser metadata is "<code>not-parser-inserted</code>", </a>`
 - [ ] LINK ERROR: No 'dfn' refs found for 'fetching a module worker script tree'. `<a data-link-type="dfn" data-lt="fetching a module worker script tree">fetching a module worker script tree</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'process the response'. `<a data-link-type="dfn" data-lt="process the response">process the response</a>`
 - [ ] LINK ERROR: Ambiguous for-less link for 'url', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
  Local references:
  - `spec:html-5.3; type:dfn; for:Location; text:url`
  for-less references:
  - `spec:url; type:dfn; for:/; text:url`
  - `<a data-link-type="dfn" data-lt="url">url</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'perform the fetch steps complete with '. `<a data-link-type="dfn" data-lt="perform the fetch steps complete with ">perform the fetch steps complete with </a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'set up the request'. `<a data-link-type="dfn" data-lt="set up the request">set up the request</a>`
 - [ ] LINK ERROR: No 'dfn' refs found for 'module record'. `<a data-link-type="dfn" data-lt="module record">module record</a>`
 - [ ] LINK ERROR: No 'dfn' refs found for 'parser state'. `<a data-link-type="dfn" data-lt="parser state">parser state</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'process the response'. `<a data-link-type="dfn" data-lt="process the response">process the response</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'optional tags'. `<a data-link-type="dfn" data-lt="optional tags">optional tags</a>`
 - [x] LINK ERROR: No 'element-sub' refs found for 'nonce' with for='link'. `<a data-link-type="element-sub" data-lt="nonce" data-link-for="link">nonce</a>`
 - [x] LINK ERROR: No 'element-sub' refs found for 'nonce' with for='style'. `<a data-link-type="element-sub" data-lt="nonce" data-link-for="style">nonce</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'valid mime type with no parameters'. `<a data-lt="valid MIME type with no parameters" data-link-type="dfn">valid MIME types with no parameters</a>`
 - [ ] LINK ERROR: No 'event' refs found for 'show'. `<a data-link-type="event" data-link-for="global" data-lt="show"><code>show</code></a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'concept-origin-effective-domain'. `<a data-lt="concept-origin-effective-domain" data-link-type="dfn">If <var>effectiveDomain</var> is null, then throw a "<code class="idl" nohighlight=""><a data-link-type="idl" data-lt="SecurityError" href="https://www.w3.org/TR/WebIDL-1/#securityerror" id="ref-for-securityerror&#9312;&#9315;" data-silently-dedup="">SecurityError</a></code>" <code class="idl" nohighlight=""><a data-link-type="idl" data-lt="DOMException" href="https://heycam.github.io/webidl/#idl-DOMException" id="ref-for-idl-DOMException&#9313;&#9319;" data-silently-dedup="">DOMException</a></code>.</a>`
 - [x] LINK ERROR: No 'dfn' refs found for 'concept-origin-effective-domain'. `<a data-lt="concept-origin-effective-domain" data-link-type="dfn">If the given value <span data-x="is a registrable domain suffix of or is equal to">is not a registrable domain suffix of and is not equal to</span> <var>effectiveDomain</var> throw a "<code class="idl" nohighlight=""><a data-link-type="idl" data-lt="SecurityError" href="https://www.w3.org/TR/WebIDL-1/#securityerror" id="ref-for-securityerror&#9312;&#9316;" data-silently-dedup="">SecurityError</a></code>" <code class="idl" nohighlight=""><a data-link-type="idl" data-lt="DOMException" href="https://heycam.github.io/webidl/#idl-DOMException" id="ref-for-idl-DOMException&#9313;&#9320;" data-silently-dedup="">DOMException</a></code>.</a>`
 - [x] WARNING: The following (probably auto-generated) link is illegally nested in another link: `<a data-link-type="idl" href="https://www.w3.org/TR/WebIDL-1/#securityerror" id="ref-for-securityerror&#9312;&#9315;" data-silently-dedup="">SecurityError</a>`
 - [x] WARNING: The following (probably auto-generated) link is illegally nested in another link: `<a data-link-type="idl" href="https://heycam.github.io/webidl/#idl-DOMException" id="ref-for-idl-DOMException&#9313;&#9319;" data-silently-dedup="">DOMException</a>`
 - [x] WARNING: The following (probably auto-generated) link is illegally nested in another link: `<a data-link-type="idl" href="https://www.w3.org/TR/WebIDL-1/#securityerror" id="ref-for-securityerror&#9312;&#9316;" data-silently-dedup="">SecurityError</a>`
 - [x] WARNING: The following (probably auto-generated) link is illegally nested in another link: `<a data-link-type="idl" href="https://heycam.github.io/webidl/#idl-DOMException" id="ref-for-idl-DOMException&#9313;&#9320;" data-silently-dedup="">DOMException</a>`
 - [x] WARNING: The following (probably auto-generated) link is illegally nested in another link: `<a data-link-type="idl" data-lt="domain" data-link-for="Document" href="#dom-document-domain" id="ref-for-dom-document-domain&#9319;" data-silently-dedup="">document.domain</a>`
 - [x] WARNING: The following (probably auto-generated) link is illegally nested in another link: `<a data-link-type="idl" data-lt="domain" data-link-for="Document" href="#dom-document-domain" id="ref-for-dom-document-domain&#9320;" data-silently-dedup="">document.domain</a>`
 - [x] WARNING: The following (probably auto-generated) link is illegally nested in another link: `<a data-link-type="idl" data-lt="domain" data-link-for="Document" href="#dom-document-domain" id="ref-for-dom-document-domain&#9312;&#9450;" data-silently-dedup="">document.domain</a>`
 - [x] WARNING: The following (probably auto-generated) link is illegally nested in another link: `<a class="self-link" href="#sandboxing"></a>`
 - [x] WARNING: The following (probably auto-generated) link is illegally nested in another link: `<a data-link-type="element-sub" data-link-for="media" href="#element-attrdef-media-disableremoteplayback" id="ref-for-element-attrdef-media-disableremoteplayback&#9318;" data-silently-dedup="">disableRemotePlayback</a>`
 - [x] WARNING: The following (probably auto-generated) link is illegally nested in another link: `<a data-link-type="idl" href="#htmlmediaelement" id="ref-for-htmlmediaelement&#9317;" data-silently-dedup="">HTMLMediaElement</a>`

(updated for formatting and clarity)

**Comment by chaals** [comment]
Whoops. There are still some warnings. Reopening so we can keep tracking

**Comment by chaals** [comment]
some fixed by #1235, some to be fixed by #1234 ...

**Comment by edent** [comment]
Down to 17 warnings!

```
LINK ERROR: Ambiguous for-less link for 'referrer policy', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:html-5.3; type:dfn; for:/; text:referrer policy
spec:html-5.3; type:dfn; for:script; text:referrer policy
for-less references:
spec:fetch; type:dfn; for:/; text:referrer policy
<a data-link-type="dfn" data-lt="referrer policy">referrer policy</a>
LINK ERROR: Ambiguous for-less link for 'referrer policy', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:html-5.3; type:dfn; for:/; text:referrer policy
spec:html-5.3; type:dfn; for:script; text:referrer policy
for-less references:
spec:fetch; type:dfn; for:/; text:referrer policy
[=referrer policy=]
LINK ERROR: Ambiguous for-less link for 'csp list', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:html-5.3; type:dfn; for:document; text:csp list
for-less references:
spec:csp; type:dfn; for:/; text:csp list
<a data-link-type="dfn" data-lt="CSP list">CSP list</a>
LINK ERROR: Ambiguous for-less link for 'referrer policy', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:html-5.3; type:dfn; for:/; text:referrer policy
spec:html-5.3; type:dfn; for:script; text:referrer policy
for-less references:
spec:fetch; type:dfn; for:/; text:referrer policy
<a data-link-type="dfn" data-lt="Referrer policy">Referrer policy</a>
LINK ERROR: No 'idl-name' refs found for 'RemotePlayback'.
<a data-link-type="idl-name" class="n" data-lt="RemotePlayback">RemotePlayback</a>
LINK ERROR: No 'dfn' refs found for 'absolute-anchored'.
<a data-link-type="dfn" data-lt="absolute-anchored">absolute-anchored</a>
LINK ERROR: No 'dfn' refs found for 'concept-host'.
<a data-lt="concept-host" data-link-type="dfn">host</a>
LINK ERROR: No 'dfn' refs found for 'concept-domain'.
<a data-lt="concept-domain" data-link-type="dfn">domain</a>
LINK ERROR: No 'dfn' refs found for 'concept-host'.
<a data-lt="concept-host" data-link-type="dfn">hosts</a>
LINK ERROR: Ambiguous for-less link for 'origin', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:html-5.3; type:dfn; for:concept; text:origin
spec:html-5.3; type:dfn; for:security; text:origin
for-less references:
spec:css-cascade-4; type:dfn; for:/; text:origin
<a data-link-type="dfn" data-lt="origin">origin</a>
LINK ERROR: Multiple possible 'items' dfn refs.
Arbitrarily chose https://infra.spec.whatwg.org/#list-item
To auto-select one of the following refs, insert one of these lines into a <pre class=link-defaults> block:
spec:infra; type:dfn; for:tuple; text:item
spec:infra; type:dfn; for:stack; text:item
spec:infra; type:dfn; for:queue; text:item
spec:infra; type:dfn; for:list; text:item
spec:infra; type:dfn; for:pair; text:item
spec:infra; type:dfn; for:set; text:item
spec:infra; type:dfn; for:struct; text:item
<a data-link-type="dfn" data-lt="items">items</a>
LINK ERROR: Ambiguous for-less link for 'url', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:html-5.3; type:dfn; for:Location; text:url
for-less references:
spec:url; type:dfn; for:/; text:url
<a data-link-type="dfn" data-lt="URL">URL</a>
LINK ERROR: No 'dfn' refs found for 'fetching a module worker script tree'.
<a data-link-type="dfn" data-lt="fetching a module worker script tree">fetching a module worker script tree</a>
LINK ERROR: Ambiguous for-less link for 'url', please see <https://tabatkins.github.io/bikeshed/#ambi-for> for instructions:
Local references:
spec:html-5.3; type:dfn; for:Location; text:url
for-less references:
spec:url; type:dfn; for:/; text:url
<a data-link-type="dfn" data-lt="url">url</a>
LINK ERROR: No 'dfn' refs found for 'module record'.
<a data-link-type="dfn" data-lt="module record">module record</a>
LINK ERROR: No 'dfn' refs found for 'parser state'.
<a data-link-type="dfn" data-lt="parser state">parser state</a>
LINK ERROR: No 'event' refs found for 'show'.
<a data-link-type="event" data-link-for="global" data-lt="show"><code>show</code></a>
 ✔  Successfully generated, with 17 linking errors
```

**Comment by cynthia** [comment]
Looks like we are down to 7 at this point - or am I seeing things?

**Comment by edent** [comment]
@cynthia down to 6 now 😀

**Comment by edent** [comment]
Closing for now as we come to the end of 5.3

Will open a new issue after publication to deal with any stragglers.
