### ISSUE TITLE
[Meta] merge custom elements

### ISSUE THREAD

**Issue by chaals** [w3c/html#1229]
As per #1209, merge the parts of the custom elements spec that are relevant into this spec.

This is a meta issue, to track the relevant set of tasks.

* [x] Move the bulk of the custom elements spec chapters 2 and 3 into HTML #1343

(Includes defining CEReactions - #911)

Apply patches described in the spec:
* [x] Add `customelements` to `Window` #1274
* [x] Define the `:defined` selector as applied to HTML #1326 
* [x] [Creating and inserting nodes in parsing](https://www.w3.org/TR/custom-elements/#html-creating-and-inserting-nodes) #1401
* [x] [Parsing for XHTML documents](https://www.w3.org/TR/custom-elements/#html-parsing-xhtml-documents) #1408
* [x] Update Content Model definitions #1276
* [ ] [Add `CEReactions` and `HTMLConstructor` IDL attributes as required](https://www.w3.org/TR/custom-elements/#html-wide-ranging-patches). A crude grep suggests in the order of 100 places in the spec to check

Other tasks
* [x] what to do with is="" attribute on regular elements #1277 
* [x] ensure the index has no terms defined in custom elements spec
* [x] define the slot attribute #1256 
* [x] define the slot element #1404

**Comment by siusin** [comment]
We're closing this issue on the W3C HTML specification because the W3C and WHATWG are now [working together on HTML](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), and all issues are being discussed on the [WHATWG repository](https://github.com/whatwg/html).
