### ISSUE TITLE
Flesh out README to contain useful information

### ISSUE THREAD

**Issue by ZoeBijl** [w3c/html#3]
While the instructions are clear, there should be more information on this project, some subjects that I feel should be in the README:
- [ ] Some background information
- [x] Who to contact for access / how to join the relevant W3C WG
- [x] More information on contributing (maybe link to CONTRIBUTING.md?): see https://github.com/w3c/html/pull/17

**Comment by chaals** [comment]
PR #45 fixes point 2. How much background do you think people really need here?

**Comment by ZoeBijl** [comment]
Hmm, I think people would be interested in the purpose of this specification and how it (will) differ(s) from the WHATWG one (like we discussed in November).

**Comment by chaals** [comment]
We think this is mostly clear. Specific pull requests welcome.

**Comment by ZoeBijl** [comment]
Maybe just link to Léonie's e-mail? I'll fix that, reopening this to remind me :)

**Comment by chaals** [comment]
@MichielBijl is there still something to do here?

**Comment by ZoeBijl** [comment]
Sorry, I can't find the original e-mail. I'll add when I can find it. Close for now.
