### ISSUE TITLE
Document working with spec and bikeshed in HTML

### ISSUE THREAD

**Issue by arronei** [w3c/html#362]
- [ ] HTML specific bikeshed data and info
- [x] how to edit the spec and helpful tips
- [x] links should not wrap lines

**Comment by travisleithead** [comment]
I think this can move to CR milestone.

**Comment by chaals** [comment]
> I think this can move to CR milestone.

OK, but it is really helpful for anyone who isn't deep in the mechanics of bikeshed and our spec who wants to help make a PR. So please don't postpone it further

**Comment by chaals** [comment]
We could still improve this, but I think we're most of the way there. The big thing missing is describing how to find out what magic names bikeshed knows, and how to add to them, but that is documented on the interwebs…
