### ISSUE TITLE
Things we will look at after 5.1

### ISSUE THREAD

**Issue by plehegar** [w3c/html#368]
Changes that were made by WHATWG to their spec, that we may want to match for interoperability, but don't believe need to be in HTML 5.1
- [ ] https://github.com/whatwg/html/commit/334f9edbf4c7c1648dcf153a393a53ea025f342e Make ImageBitmap transferable
- [x] https://github.com/whatwg/html/commit/87c078dfd7c36d65328db4bb7bfc3c8f411e5997
- [ ] https://github.com/whatwg/html/commit/cd1a9fb1e83f7d0bc30be8b34ecdaf444a0b19a4 Add `<script type="module">` and module resolution/fetching/evaluation
- [ ] https://github.com/whatwg/html/commit/ee77b8710cea05aa1c56b32b9d7d790c39a62aef allow skipping rendering updates for nested browsing contexts like `iframe`, intended chrome experiment
- [x] https://github.com/whatwg/html/commit/130af62724bff8b627587e2eafd8496d4c69cf69
- [x] https://github.com/whatwg/html/commit/faec3a50ea181f322ab9819975e285ced34a0308
- [ ] https://github.com/whatwg/html/commit/3c047b5a35da7af9cffef2a654a944e33be256cc Fix fetching module scripts with circular imports
- [ ] https://github.com/whatwg/html/commit/dad854e4c1f5f7098a1b1ec7f33e2218796f7442 Make DOM define Window as parent of document for event dispatch
- [ ] https://github.com/whatwg/html/commit/e3a5bb757f64374c37d8c4528c01298463ef0b2a Add module workers
- [ ] https://github.com/whatwg/html/commit/2a03759f2fbf4199d187c046074d574a9ae0e209 Revamp definition of `document.domain`
- [ ] https://github.com/whatwg/html/commit/05e4a1f6c4941273baa647b8e889d2db7fd9bd88 Define `<meta name="theme-color">`
- [ ] https://github.com/whatwg/html/commit/9194856d7b5a91aa910640e5686048317924e7aa clarify control groups and control group owner objects for in describing _focusable things_.
- [ ] https://github.com/whatwg/html/commit/07f6c7f058c57d582db1aced6741cea1ed63ccf7 Use [LegacyUnenumerableNamedProperties] in IDL
- [ ] https://github.com/whatwg/html/commit/026aa966c944ce0f1180bc906646c00a3f7ebcbb Let Fetch define the default User-Agent value
- [ ] https://github.com/whatwg/html/commit/9a889fee2ecb106974fb48fa50491edd77047954 Move module map to Document/WorkerGlobalScope
- [ ] https://github.com/whatwg/html/commit/36c9938b102fecadf6029a248f40aae83ea099d2 Let DOM defines the `class`, `id`, and Shadow DOM's `slot` attributes
- [ ] https://github.com/whatwg/html/commit/5af258f33e3e2f55eb30e611cb7aee625a8bd16a Sync with recent changes to the JS spec's job queue in tc39/ecma262@7032383 
- [ ] https://github.com/whatwg/html/commit/baa8e346d737c115d4a676caa4a172983b87255e Set `<template>`'s DocumentFragment's host
- [ ] https://github.com/whatwg/html/commit/21c6ec77594eb89b836d4872222f5916910967fd Editorial alignment to whatwg DOM - needed?
- [ ] https://github.com/whatwg/html/commit/2971950c4078d999aa9dbbc0aa0628f76d9d53f7 Use FrozenArray for location.ancestorOrigins
- [ ] https://github.com/whatwg/html/commit/6bdba31102d6aea442b215fe485093c0ad322425 Introduce `self.origin`
- [ ] https://github.com/whatwg/html/commit/cdd48e1f570c817402bf62108847c4a9f4b00b1e Editorial: put properties shared across globals on mixin
- [ ] https://github.com/whatwg/html/commit/e4df68a41b86753c7fcdd0d8ea4615f63ffc87e9 Use FrozenArray for Navigator#languages and MessageEvent#ports
- [ ] https://github.com/whatwg/html/commit/fc927e65ceab229209f116866a76b1c618b9a1d4 Let DOM define "create an element"
- [ ] https://github.com/whatwg/html/commit/69182823e3dae507380fa9a70d26fe7b51ae62ac Don't update document.currentScript for module scripts
- [ ] https://github.com/whatwg/html/commit/9b2320f69c159c4dc9cc1d06f1494b9da3a23054 Editorial - add `id`s to the `<script type="module">` examples
- [ ] https://github.com/whatwg/html/commit/b46dae73cde338737baa917102e93352036eeff6 Add navigator.oscpu in Gecko compatability mode
- [ ] https://github.com/whatwg/html/commit/b66ec320db01c12d48176052c3b9cd55a10f3176 Refactoring in the parsing of names / attributes
- [ ] https://github.com/whatwg/html/commit/caf203fd4d9a5047d1ff2edad2290d53e21368ba make `script>` work in Shadow DOM trees
- [x] https://github.com/whatwg/html/commit/817da9577b565e808d7af0295e1affc094887418
- [ ] https://github.com/whatwg/html/commit/8da5a18b447290ffcdd6c23e268a6e75f906c684 Define insert into/remove from document for all nodes, in line with DOM version.
- [ ] https://github.com/whatwg/html/commit/3c157377135d05fbdd74f8c69199b47408bc6a9a
- [ ] https://github.com/whatwg/html/commit/927fda0f305452a9c54a25d3ebf9a6ed5ae29fd3
- [ ] https://github.com/whatwg/html/commit/a082daa4aa272f4eae77b67aa3116af482f03e5e Editorial: rename ElementRegistrationOptions to ElementDefinitionOptions
- [ ] https://github.com/whatwg/html/commit/3210b7c67ed07fec1d9b69134ced8111825c740e
- [ ] https://github.com/whatwg/html/commit/6a7318072f340ad45229df171245d70d8621c2fe Integration with Referrer Policy (partial)
- [ ] https://github.com/whatwg/html/commit/24ab0606cb83dbad6e9ee627b4d8fc55a9bb5f5a Fix links to IntersectionObserver spec
- [ ] https://github.com/whatwg/html/commit/3828d49503284ff790c993f1c9218b4d982cfe75 Define 'HTTPS state' in terms of fetch
- [ ] https://github.com/whatwg/html/commit/c9d898386d7b79cf1c7e104b5768e393c924078f Fix owner document for element constructors
- [ ] https://github.com/whatwg/html/commit/a021607e61e78e7d24e9db857307948ea4379667 Feed auto-discovery only applies to `<link>`

Incubate first:
- https://github.com/whatwg/html/commit/87b8402079f63cc6adfd2b21fb67231a02f00933 Add navigator.hardwareConcurrency

(makes sure this doesn't end up in 5.1)
- https://github.com/whatwg/html/commit/0fef169e6fca7433e3aac2a3640b4665b791ff8e

(check implementation)
- [ ] https://github.com/whatwg/html/commit/be8edde20ac46786af968d4de23e90801d4c7213 Make `HTMLMediaElement.prototype.play()` return a promise

As reviewed on the 7 June 2016 HTML Editors teleconference:
- [ ] https://github.com/whatwg/html/commit/4b4c941e58849da433a2e7706642db222476e536 - formalize character refs. Good to take.
- [ ] https://github.com/whatwg/html/commit/190b1efc010f70df4ad2208112408b7e11fa3946 - sync an algorithm
- [x] https://github.com/whatwg/html/commit/199cd153b15865366bae3170a26be2431e7e589b  already done
- [x] https://github.com/whatwg/html/commit/da9e4cb7142277d609e6636a56a282f5aba15e5c - area.ping -> DOMTokenList
- [ ] https://github.com/whatwg/html/commit/da9e4cb7142277d609e6636a56a282f5aba15e5c - logical props for rendering section
- [ ] https://github.com/whatwg/html/commit/da9e4cb7142277d609e6636a56a282f5aba15e5c - referrer policy spec integration
- [ ] https://github.com/whatwg/html/commit/da9e4cb7142277d609e6636a56a282f5aba15e5c - import statements for referrer
- [ ] https://github.com/whatwg/html/commit/7ff5b096d423bf5750463957aed69680368ed99e - User agents _should_ treat `<link rel=next>` as `rel={prefetch,prerender…}` (but not `a rel=…`)
- [ ] https://github.com/whatwg/html/commit/ea2f021c265bd082415f2775fc7a1c562ec7275a - more clear contentDocument
- [ ] https://github.com/whatwg/html/commit/cf2bcf17ad2b9f01c7ebee12f7b8728bb7e4cbcb - update execCommands linking (may not be relevant)
- [ ] https://github.com/whatwg/html/commit/8ef5d945d9c4298a0d66f81543f6a7e83634f39b - EDITORIAL - before unload optional prompt
- [ ] https://github.com/whatwg/html/commit/bbfba9a01672be45de3a447f926c65568ce7e086 - image request init to "imageset"
- [ ] https://github.com/whatwg/html/commit/bbfba9a01672be45de3a447f926c65568ce7e086 - USVString for all URLs
- [ ] https://github.com/whatwg/html/commit/7707b72cbb628c439252c1e297f6284396a95d8b - EDITORIAL - typo in nonce
- [ ] https://github.com/whatwg/html/commit/8d564d1b5589906f77589b499e1ebf44671d2ee6 - "pause" warning
- [ ] https://github.com/whatwg/html/commit/8d564d1b5589906f77589b499e1ebf44671d2ee6 - CSP reference updates
- [ ] https://github.com/whatwg/html/commit/c35553e4d9e1a05d33d89fa1c399d89e3290ccf4 - Module script note

(ended working up to and including May 23, 2016)

Integrating Shadow DOM
- [ ] https://github.com/whatwg/html/commit/3c157377135d05fbdd74f8c69199b47408bc6a9a add `<slot>` element
- [ ] https://github.com/whatwg/html/commit/4cf3a825211a69791a2cdbd472ce13e7addb98fe make image maps work in shadow trees
- [ ] https://github.com/whatwg/html/commit/89d97c82e498492351682ea2a4e4dbf87f583f2f make style work in shadow trees
- [ ] https://github.com/whatwg/html/commit/3210b7c67ed07fec1d9b69134ced8111825c740e make `<style>` work in disconnected shadow trees
- [ ] https://github.com/whatwg/html/commit/927fda0f305452a9c54a25d3ebf9a6ed5ae29fd3 make forms work in shadow trees
  From 5 July 2016
- [ ] https://github.com/whatwg/html/commit/fc90400dfd72fd99072668248161c90c993014bc - fragments for documents

As reviewed on the 5 July 2016 HTML Editors teleconference:
- [ ] https://github.com/whatwg/html/commit/9b4394f9a03d6910b772f17252259d99f208ce73 - glossary and linking
- [ ] https://github.com/whatwg/html/commit/177b8a506931a51ecaeae71d4518431ee01ce783 - editorial: DOMStringmap doesn't apply to microdata
- [ ] https://github.com/whatwg/html/commit/00dcb3cf4002c67099bfee22ddad743f04d4541f - editorial
- [ ] https://github.com/whatwg/html/commit/c63078741df8ae8c4657dc068d5879fb3472dee6 - real-world compat for location.hash="", change works in FF/Yandex, tested manually in console
- [ ] https://github.com/whatwg/html/commit/a932f7dfd5e50101db47a373cee27b04ed108934 - linking
- [ ] https://github.com/whatwg/html/commit/e2d80d9285976c6c38bda188c59e97456006d0a3 - Remove form submission to data: URIs
- [ ] https://github.com/whatwg/html/commit/69ea9df17bf1d7d70a2014c6d2aaf16670683feb - editorial
- [ ] https://github.com/whatwg/html/commit/4820c3cad60e8e55176b27d1e7249fc59ee9b22c - editorial (tiny)
- [ ] https://github.com/whatwg/html/commit/98895af2179ad879da9fa57983ab9589251f7950 - fix interop popstate/hashchange

(ended working up to and including May 27, 2016)

Integrating Screen Orientation
- [ ] https://github.com/whatwg/html/commit/8f0f73c1b061a8ccee57c6878d8474b43c73aaeb - allow-orientation-lock

Integrating Presentation API
- [ ] https://github.com/whatwg/html/commit/0678e3de01a3ef83c5f6f0c017e7464ede1d8ec1

**Comment by plehegar** [comment]
https://github.com/whatwg/html/commit/a021607e61e78e7d24e9db857307948ea4379667
https://github.com/whatwg/html/commit/4cf3a825211a69791a2cdbd472ce13e7addb98fe
https://github.com/whatwg/html/commit/89d97c82e498492351682ea2a4e4dbf87f583f2f

**Comment by travisleithead** [comment]
As reviewed on the 7 June 2016 HTML Editors teleconference:
- [ ] https://github.com/whatwg/html/commit/4b4c941e58849da433a2e7706642db222476e536 - formalize character refs. Good to take.
- [ ] https://github.com/whatwg/html/commit/190b1efc010f70df4ad2208112408b7e11fa3946 - sync an algorithm
- [x] https://github.com/whatwg/html/commit/199cd153b15865366bae3170a26be2431e7e589b  already done
- [x] https://github.com/whatwg/html/commit/da9e4cb7142277d609e6636a56a282f5aba15e5c - area.ping -> DOMTokenList
- [ ] https://github.com/whatwg/html/commit/da9e4cb7142277d609e6636a56a282f5aba15e5c - logical props for rendering section
- [ ] https://github.com/whatwg/html/commit/da9e4cb7142277d609e6636a56a282f5aba15e5c - referrer policy spec integration
- [ ] https://github.com/whatwg/html/commit/da9e4cb7142277d609e6636a56a282f5aba15e5c - import statements for referrer
- [ ] https://github.com/whatwg/html/commit/7ff5b096d423bf5750463957aed69680368ed99e - User agents _should_ treat `<link rel=next>` as `rel={prefetch,prerender…}` (but not `a rel=…`)
- [ ] https://github.com/whatwg/html/commit/ea2f021c265bd082415f2775fc7a1c562ec7275a - more clear contentDocument
- [ ] https://github.com/whatwg/html/commit/cf2bcf17ad2b9f01c7ebee12f7b8728bb7e4cbcb - update execCommands linking (may not be relevant)
- [ ] https://github.com/whatwg/html/commit/8ef5d945d9c4298a0d66f81543f6a7e83634f39b - EDITORIAL - before unload optional prompt
- [ ] https://github.com/whatwg/html/commit/bbfba9a01672be45de3a447f926c65568ce7e086 - image request init to "imageset"
- [ ] https://github.com/whatwg/html/commit/bbfba9a01672be45de3a447f926c65568ce7e086 - USVString for all URLs
- [ ] https://github.com/whatwg/html/commit/7707b72cbb628c439252c1e297f6284396a95d8b - EDITORIAL - typo in nonce
- [ ] https://github.com/whatwg/html/commit/8d564d1b5589906f77589b499e1ebf44671d2ee6 - "pause" warning
- [ ] https://github.com/whatwg/html/commit/8d564d1b5589906f77589b499e1ebf44671d2ee6 - CSP reference updates
- [ ] https://github.com/whatwg/html/commit/c35553e4d9e1a05d33d89fa1c399d89e3290ccf4 - Module script note

(ended working up to and including May 23, 2016)

**Comment by chaals** [comment]
Integrating Custom Elements into the spec has been split out to #569

**Comment by chaals** [comment]
Integrating Shadow DOM
- [ ] https://github.com/whatwg/html/commit/3c157377135d05fbdd74f8c69199b47408bc6a9a add `<slot>` element
- [ ] https://github.com/whatwg/html/commit/4cf3a825211a69791a2cdbd472ce13e7addb98fe make image maps work in shadow trees
- [ ] https://github.com/whatwg/html/commit/89d97c82e498492351682ea2a4e4dbf87f583f2f make style work in shadow trees
- [ ] https://github.com/whatwg/html/commit/3210b7c67ed07fec1d9b69134ced8111825c740e make `<style>` work in disconnected shadow trees
- [ ] https://github.com/whatwg/html/commit/927fda0f305452a9c54a25d3ebf9a6ed5ae29fd3 make forms work in shadow trees
  From 5 July 2016
- [ ] https://github.com/whatwg/html/commit/fc90400dfd72fd99072668248161c90c993014bc - fragments for documents

**Comment by travisleithead** [comment]
As reviewed on the 5 July 2016 HTML Editors teleconference:
- [ ] https://github.com/whatwg/html/commit/9b4394f9a03d6910b772f17252259d99f208ce73 - glossary and linking
- [ ] https://github.com/whatwg/html/commit/177b8a506931a51ecaeae71d4518431ee01ce783 - editorial: DOMStringmap doesn't apply to microdata
- [ ] https://github.com/whatwg/html/commit/00dcb3cf4002c67099bfee22ddad743f04d4541f - editorial
- [ ] https://github.com/whatwg/html/commit/c63078741df8ae8c4657dc068d5879fb3472dee6 - real-world compat for location.hash="", change works in FF/Yandex, tested manually in console
- [ ] https://github.com/whatwg/html/commit/a932f7dfd5e50101db47a373cee27b04ed108934 - linking
- [ ] https://github.com/whatwg/html/commit/e2d80d9285976c6c38bda188c59e97456006d0a3 - Remove form submission to data: URIs
- [ ] https://github.com/whatwg/html/commit/69ea9df17bf1d7d70a2014c6d2aaf16670683feb - editorial
- [ ] https://github.com/whatwg/html/commit/4820c3cad60e8e55176b27d1e7249fc59ee9b22c - editorial (tiny)
- [ ] https://github.com/whatwg/html/commit/98895af2179ad879da9fa57983ab9589251f7950 - fix interop popstate/hashchange

(ended working up to and including May 27, 2016)

**Comment by travisleithead** [comment]
Integrating Screen Orientation
- [ ] https://github.com/whatwg/html/commit/8f0f73c1b061a8ccee57c6878d8474b43c73aaeb - allow-orientation-lock

Integrating Presentation API
- [ ] https://github.com/whatwg/html/commit/0678e3de01a3ef83c5f6f0c017e7464ede1d8ec1

**Comment by arronei** [comment]
Closing issue since we are syncing using a different method now
