### ISSUE TITLE
How to Build HTML5+ specification for non w3c/html repositories, focus on translations

### ISSUE THREAD

**Issue by fititnt** [w3c/html#633]
Related to #588

---
## Key points
- [ ] 1. Basic instructions on how to build documentation for non w3c/html repositories
- [ ] 2. By default, do not allow be indexed by search engines
- [ ] 3. For forks, should _be easy_ to change branch (i.e. someone translating just one part)
- [ ] 4. If item 1 is too advanced, make it more simple (can be ignored)
## Explanation

For at some point on future allow translations of HTML5+ spec with tracking of updates is important to document how to build the spec.

Since it is possible that some contributions are from people that have no technical experience to have on local machines bikeshed and multipage (that, for now, uses a lot of ram), people after hours can "end up translating something wrong" and breaking up and waste a lot of time.

This issue is about to document, or even change original repository, to allow build from forks and forks of forks.

One additional problem, that w3c/html repository does not have, but after this change would have, is that these forks, by default, should not allow index by search engines. 
## Workflow example
1. Org ACME set up a Esperanto translation of HTML 5.1 based on a fork of w3c/html
2. Bob want to help. Fork ACME repo. He does not know what is Travis.
3. Alice ask Bob to install Teamviewer and ask his skype/hangout.
4. Alice, in less than 40min, with Teamviewer, setup HTML build on his fork, and explain more information on how to contribute. She even make his first commit in pair programming
5. Bob start the translation. Open a pull request on ACME repository
6. Bob make a wrong change and brake build. He already know what commit, so is easier for solve without ask Alice
7. Bob says ok PR that is ready for merge
8. Alice check bob.github.io/html-esperanto on https://validator.w3.org/ and compare if have more errors. Find few simple errors like `<em>xpto<em>`. Ask bob if he want to resolve or she accept PR and do it on master branch.
9. Bob make the changes. 
10. PR is accepted

**Comment by chaals** [comment]
@siusin can you help explain the build process?

**Comment by travisleithead** [comment]
This is outside of my expertise. Someone who know more about the infrastructure may be able to take this?

**Comment by ahmadalfy** [comment]
Are we talking about using [bikeshed](https://tabatkins.github.io/bikeshed/)?

**Comment by LJWatson** [comment]
@ahmadalfy, the spec uses Bikeshed, yes.

**Comment by LJWatson** [comment]
We can try to help with shorter issues that focus on specific questions, but otherwise I'm afraid this issue is beyond our scope. It may be worth contacting w3c-translators@w3.org for help though.
